import React,{useEffect,useState}from'react';
import{coach,fmtWeight,lastExercise}from'./logic/progression.js';
import{DEFAULT_PROGRAMME,cloneProgramme,dayExercises}from'./logic/programme.js';
import{exercisePRs,workoutStats}from'./logic/analytics.js';
import{loadStore,saveStore}from'./storage/storage.js';

export default function App(){
 const initial=loadStore(),[tab,setTab]=useState('home'),[sessions,setSessions]=useState(initial.sessions||[]),[programme,setProgramme]=useState(initial.programme||cloneProgramme()),[workout,setWorkout]=useState(null),[restEnd,setRestEnd]=useState(null),[seconds,setSeconds]=useState(0),[selected,setSelected]=useState('');
 useEffect(()=>saveStore({sessions,programme,settings:{}}),[sessions,programme]);
 useEffect(()=>{if(!restEnd)return;const tick=()=>{const n=Math.max(0,Math.ceil((restEnd-Date.now())/1000));setSeconds(n);if(!n)setRestEnd(null)};tick();const id=setInterval(tick,250);return()=>clearInterval(id)},[restEnd]);
 useEffect(()=>{const wake=()=>restEnd&&setSeconds(Math.max(0,Math.ceil((restEnd-Date.now())/1000)));document.addEventListener('visibilitychange',wake);window.addEventListener('pageshow',wake);window.addEventListener('focus',wake);return()=>{document.removeEventListener('visibilitychange',wake);window.removeEventListener('pageshow',wake);window.removeEventListener('focus',wake)}},[restEnd]);
 const next=programme[sessions.length%programme.length]||programme[0],finish=s=>{setSessions(p=>[...p,s]);setWorkout(null);setTab('history')},del=id=>{if(confirm('Delete this completed workout?\n\nIt will be removed from History, Progress, PRs and future coaching comparisons.'))setSessions(p=>p.filter(s=>s.id!==id))};
 return <div className="app"><header><b>▰ HYPERTROPHY</b><span>8-WEEK BUILD</span></header><main>{workout?<Workout day={workout}sessions={sessions}finish={finish}back={()=>setWorkout(null)}rest={s=>setRestEnd(Date.now()+s*1000)}/>:tab==='home'?<Home next={next}start={()=>setWorkout(next)}sessions={sessions}/>:tab==='history'?<History sessions={sessions}del={del}/>:tab==='progress'?<Progress sessions={sessions}selected={selected}setSelected={setSelected}/>:<Programme programme={programme}setProgramme={setProgramme}/>}</main>{seconds>0&&<div className="restbar"><b>REST {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</b><button onClick={()=>setRestEnd(null)}>STOP</button></div>}<nav>{[['home','⌂','Home'],['history','▤','History'],['progress','↗','Progress'],['programme','⚙','Programme']].map(([id,i,l])=><button key={id}className={tab===id?'active':''}onClick={()=>setTab(id)}><strong>{i}</strong>{l}</button>)}</nav></div>
}
function Home({next,start,sessions}){const s=workoutStats(sessions),last=sessions.slice().sort((a,b)=>b.date.localeCompare(a.date))[0];return <><section className="card next"><small>NEXT WORKOUT</small><h1>{next.name}</h1><p>{next.exercises.length} exercises · progressive overload</p><button onClick={start}>START WORKOUT</button></section><div className="grid"><Stat n={s.workouts}l="Workouts"/><Stat n={s.volume?Math.round(s.volume).toLocaleString()+' kg':'—'}l="Volume"/><Stat n={s.sets}l="Sets"/><Stat n={s.reps}l="Reps"/></div>{last&&<section className="card"><h3>Last workout</h3><p>{last.dayName} · {new Date(last.date).toLocaleDateString('en-GB')} · {last.sets} sets</p></section>}<section className="card"><h3>Coach</h3><p><b>Progression first.</b> Every exercise uses your actual last load and reps. Beat the reps at the same load; once every prescribed set reaches the top of the range, increase the weight.</p></section></>}
function Stat({n,l}){return <div className="stat"><b>{n}</b><small>{l}</small></div>}
function Workout({day,sessions,finish,back,rest}){const[e,setE]=useState(Object.fromEntries(day.exercises.map(([n,c])=>[n,Array.from({length:c},()=>({}))]))),[start]=useState(Date.now());const upd=(n,i,k,v)=>setE(p=>({...p,[n]:p[n].map((x,j)=>j===i?{...x,[k]:v}:x)}));const done=()=>{const exercises=day.exercises.map(([name])=>({name,sets:e[name].filter(x=>x.weight!==''&&x.reps!=='').map(x=>({weight:Number(x.weight),reps:Number(x.reps)}))})).filter(x=>x.sets.length);if(!exercises.length)return alert('Log at least one set before finishing.');const volume=exercises.reduce((a,x)=>a+x.sets.reduce((b,y)=>b+y.weight*y.reps,0),0);finish({id:crypto.randomUUID(),date:new Date().toISOString(),dayName:day.name,duration:Math.max(1,Math.round((Date.now()-start)/60000)),exercises,sets:exercises.reduce((a,x)=>a+x.sets.length,0),volume})};return <><div className="topline"><button onClick={back}>‹ Back</button><b>{day.name}</b></div>{day.exercises.map(([name,count,min,max,inc])=><Exercise key={name}name={name}count={count}min={min}max={max}increment={inc}previous={lastExercise(sessions,name)}values={e[name]}update={upd}rest={rest}/>)}<button className="finish"onClick={done}>FINISH WORKOUT</button></>}
function Exercise({name,count,min,max,increment,previous,values,update,rest}){const c=coach({name,sets:count,min,max,increment},previous);return <section className="exercise"><div className="exhead"><b>{name}</b><span>{count} sets · {min}–{max} reps</span></div><div className={`coach ${c.tone}`}><strong>{c.headline}</strong><small>{c.detail}</small></div><div className="setlabels"><span>SET</span><span>KG</span><span>REPS</span></div>{values.map((x,i)=><div className="set"key={i}><span>{i+1}</span><input inputMode="decimal"placeholder={c.weight?fmtWeight(c.weight):'kg'}value={x.weight??''}onChange={e=>update(name,i,'weight',e.target.value)}/><input inputMode="numeric"placeholder={`${min}–${max}`}value={x.reps??''}onChange={e=>update(name,i,'reps',e.target.value)}/></div>)}<button className="rest"onClick={()=>rest(120)}>Start 2:00 rest</button></section>}
function History({sessions,del}){const list=sessions.slice().sort((a,b)=>b.date.localeCompare(a.date));return <><h2>Workout History</h2>{list.length?list.map(s=><section className="card hist"key={s.id}><div className="histhead"><b>{s.dayName}</b><small>{new Date(s.date).toLocaleDateString('en-GB')}</small></div><p>{s.sets} sets · {Math.round(s.volume).toLocaleString()} kg · {s.duration||0} min</p><button className="delete"onClick={()=>del(s.id)}>Delete workout</button></section>):<section className="card">No completed workouts yet.</section>}</>}
function Progress({sessions,selected,setSelected}){const names=[...new Set(sessions.flatMap(s=>s.exercises?.map(e=>e.name)||[]))],name=selected||names[0]||'',rows=name?exercisePRs(sessions,name):[],max=Math.max(1,...rows.map(r=>r.weight));return <><h2>Progress</h2><section className="card"><div className="selectrow"><b>Exercise</b><select value={name}onChange={e=>setSelected(e.target.value)}>{names.map(n=><option key={n}>{n}</option>)}</select></div>{name?<><div className="chart">{rows.slice(-12).map((r,i)=><div className="barwrap"key={i}><i style={{height:`${Math.max(12,r.weight/max*100)}px`}}/><small>{fmtWeight(r.weight)}</small></div>)}</div>{rows.filter(r=>r.prWeight||r.prStrength).slice(-8).reverse().map((r,i)=><p key={i}>🏆 {new Date(r.date).toLocaleDateString('en-GB')} · {fmtWeight(r.weight)} kg × {r.reps}</p>)}</>:<p>Complete a workout to start tracking exercise progress.</p>}</section></>}
function Programme({programme,setProgramme}){const[editing,setEditing]=useState(null),[form,setForm]=useState(null);const open=d=>{setEditing(d.id);setForm(JSON.parse(JSON.stringify(d)))};const save=()=>{setProgramme(p=>p.map(d=>d.id===form.id?form:d));setEditing(null)};return <><h2>Programme</h2>{programme.map(d=>editing===d.id?<section className="card"key={d.id}><input className="wide"value={form.name}onChange={e=>setForm({...form,name:e.target.value})}/>{form.exercises.map((x,i)=><div className="editrow"key={i}><input value={x[0]}onChange={e=>{const a=[...form.exercises];a[i]=[e.target.value,...a[i].slice(1)];setForm({...form,exercises:a})}}/><input value={x[1]}onChange={e=>{const a=[...form.exercises];a[i]=[a[i][0],Number(e.target.value),...a[i].slice(2)];setForm({...form,exercises:a})}}/><input value={x[2]}onChange={e=>{const a=[...form.exercises];a[i]=[a[i][0],a[i][1],Number(e.target.value),a[i][3],a[i][4]];setForm({...form,exercises:a})}}/><input value={x[3]}onChange={e=>{const a=[...form.exercises];a[i]=[a[i][0],a[i][1],a[i][2],Number(e.target.value),a[i][4]];setForm({...form,exercises:a})}}/></div>)}<button onClick={save}>SAVE CHANGES</button><button className="secondary"onClick={()=>setEditing(null)}>CANCEL</button></section>:<section className="card"key={d.id}><div className="histhead"><b>{d.name}</b><button className="link"onClick={()=>open(d)}>Edit</button></div>{dayExercises(d).map((x,i)=><p key={i}>{x.sets} × {x.min}–{x.max} · {x.name}</p>)}</section>)}</>}
