import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';
import{coach,fmtWeight,lastExercise}from'./logic/progression.js';

const PROGRAMME=[
{id:'upper-a',name:'Upper A',exercises:[['Incline DB Press',3,6,10,2.5],['Chest-Supported T-Bar Row',4,6,10,2.5],['Flat DB Press',3,8,12,2.5],['Cable Row',3,8,12,2.5],['Cable Fly',3,10,15,2.5],['Bayesian Cable Curl',3,8,12,2.5],['Overhead Cable Triceps Extension',3,10,15,2.5]]},
{id:'lower-a',name:'Lower A',exercises:[['RDL',3,6,10,5],['Hip Thrust',4,8,12,5],['Leg Curl',4,8,12,2.5],['Leg Press',2,8,12,5],['Abs',3,10,15,2.5]]},
{id:'upper-b',name:'Upper B',exercises:[['DB Shoulder Press',3,6,10,2.5],['Chest-Supported T-Bar Row',3,8,12,2.5],['Incline DB Press',3,8,12,2.5],['Cable Row',3,8,12,2.5],['Cable Lateral Raise',3,10,15,2.5],['DB Curl',3,8,12,2.5],['Cable Triceps Extension',3,10,15,2.5]]},
{id:'lower-b',name:'Lower B',exercises:[['RDL',3,6,10,5],['Hip Thrust',3,8,12,5],['Leg Curl',4,8,12,2.5],['Pendulum Squat',3,8,12,5],['Abs',3,10,15,2.5]]}];
const KEY='ht_sessions';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};const save=v=>localStorage.setItem(KEY,JSON.stringify(v));
function App(){const[tab,setTab]=useState('home'),[sessions,setSessions]=useState(load),[workout,setWorkout]=useState(null),[restEnd,setRestEnd]=useState(null),[seconds,setSeconds]=useState(0);const next=PROGRAMME[sessions.length%PROGRAMME.length];
useEffect(()=>{if(!restEnd)return;const tick=()=>{const n=Math.max(0,Math.ceil((restEnd-Date.now())/1000));setSeconds(n);if(!n)setRestEnd(null)};tick();const id=setInterval(tick,250);return()=>clearInterval(id)},[restEnd]);
useEffect(()=>{const wake=()=>restEnd&&setSeconds(Math.max(0,Math.ceil((restEnd-Date.now())/1000)));document.addEventListener('visibilitychange',wake);window.addEventListener('pageshow',wake);window.addEventListener('focus',wake);return()=>{document.removeEventListener('visibilitychange',wake);window.removeEventListener('pageshow',wake);window.removeEventListener('focus',wake)}},[restEnd]);
const finish=s=>{const n=[...sessions,s];setSessions(n);save(n);setWorkout(null);setTab('history')};const del=id=>{if(!confirm('Delete this completed workout?\n\nIt will be removed from History, Progress and coaching comparisons.'))return;const n=sessions.filter(s=>s.id!==id);setSessions(n);save(n)};
return <div className="app"><header><b>▰ HYPERTROPHY</b><span>8-WEEK BUILD</span></header><main>{workout?<Workout day={workout} sessions={sessions} onFinish={finish} onBack={()=>setWorkout(null)} onRest={s=>setRestEnd(Date.now()+s*1000)}/>:tab==='home'?<Home next={next} start={()=>setWorkout(next)} sessions={sessions}/>:tab==='history'?<History sessions={sessions} onDelete={del}/>:tab==='progress'?<Progress sessions={sessions}/>:<Programme/>}</main>{seconds>0&&<div className="restbar"><b>REST {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</b><button onClick={()=>setRestEnd(null)}>STOP</button></div>}<nav>{[['home','⌂','Home'],['history','▤','History'],['progress','↗','Progress'],['programme','⚙','Programme']].map(([id,i,l])=><button className={tab===id?'active':''}onClick={()=>setTab(id)}key={id}><strong>{i}</strong>{l}</button>)}</nav></div>}
function Home({next,start,sessions}){const recent=sessions[0];return <><section className="card next"><small>NEXT WORKOUT</small><h1>{next.name}</h1><p>{next.exercises.length} exercises · progressive overload</p><button onClick={start}>START WORKOUT</button></section><div className="grid"><Stat n={sessions.length}l="Workouts"/><Stat n={sessions.length?Math.round(sessions.reduce((a,s)=>a+s.volume,0)).toLocaleString()+' kg':'—'}l="Total volume"/></div>{recent&&<section className="card"><h3>Last workout</h3><p>{recent.dayName} · {new Date(recent.date).toLocaleDateString('en-GB')}</p></section>}<section className="card"><h3>Coach</h3><p>Every exercise shows your exact last load/reps and today's target. Beat reps first; increase weight when every prescribed set reaches the top of its range.</p></section></>}
function Stat({n,l}){return <div className="stat"><b>{n}</b><small>{l}</small></div>}
function Workout({day,sessions,onFinish,onBack,onRest}){const[entries,setEntries]=useState(()=>Object.fromEntries(day.exercises.map(([name,count])=>[name,Array.from({length:count},()=>({}))])));const[started]=useState(Date.now());const update=(name,i,k,v)=>setEntries(p=>({...p,[name]:p[name].map((x,j)=>j===i?{...x,[k]:v}:x)}));const finish=()=>{const exercises=day.exercises.map(([name,count])=>({name,sets:(entries[name]||[]).filter(x=>x.weight&&x.reps).map(x=>({weight:Number(x.weight),reps:Number(x.reps)}))})).filter(e=>e.sets.length);const volume=exercises.reduce((a,e)=>a+e.sets.reduce((b,x)=>b+x.weight*x.reps,0),0);onFinish({id:crypto.randomUUID(),date:new Date().toISOString(),dayName:day.name,duration:Math.round((Date.now()-started)/60000),exercises,sets:exercises.reduce((a,e)=>a+e.sets.length,0),volume})};return <><div className="topline"><button onClick={onBack}>‹ Back</button><b>{day.name}</b></div>{day.exercises.map(([name,count,min,max,increment])=><Exercise key={name}name={name}count={count}min={min}max={max}increment={increment}previous={lastExercise(sessions,name)}values={entries[name]}update={update}onRest={onRest}/>)}<button className="finish"onClick={finish}>FINISH WORKOUT</button></>}
function Exercise({name,count,min,max,increment,previous,values,update,onRest}){const c=coach({name,sets:count,min,max,increment},previous);return <section className="exercise"><div className="exhead"><b>{name}</b><span>{count} × {min}–{max}</span></div><div className={`coach ${c.tone}`}><strong>{c.headline}</strong><small>{c.detail}</small></div>{values.map((x,i)=><div className="set"key={i}><span>{i+1}</span><input inputMode="decimal"placeholder={c.weight?fmtWeight(c.weight):'kg'}value={x.weight??''}onChange={e=>update(name,i,'weight',e.target.value)}/><input inputMode="numeric"placeholder={`${min}–${max}`}value={x.reps??''}onChange={e=>update(name,i,'reps',e.target.value)}/></div>)}<button className="rest"onClick={()=>onRest(120)}>Start 2:00 rest</button></section>}
function History({sessions,onDelete}){const sorted=sessions.slice().sort((a,b)=>b.date.localeCompare(a.date));return <><h2>Workout History</h2>{sorted.length?sorted.map(s=><section className="card hist"key={s.id}><div><b>{s.dayName}</b><small>{new Date(s.date).toLocaleDateString('en-GB')}</small></div><p>{s.sets} sets · {Math.round(s.volume).toLocaleString()} kg volume{s.duration?` · ${s.duration} min`:''}</p><button className="delete"onClick={()=>onDelete(s.id)}>Delete workout</button></section>):<section className="card">No completed workouts yet.</section>}</>}
function Progress({sessions}){const items=sessions.slice().sort((a,b)=>a.date.localeCompare(b.date)).slice(-8);return <><h2>Progress</h2><section className="card"><b>{sessions.length}</b><p>completed workouts</p><div className="bars">{items.map(s=><i key={s.id}style={{height:Math.max(12,Math.min(100,s.volume/100))+'px'}}title={`${Math.round(s.volume)} kg`}/>)}</div></section></>}
function Programme(){return <><h2>Programme</h2>{PROGRAMME.map(d=><section className="card"key={d.id}><b>{d.name}</b>{d.exercises.map(([name,count,min,max])=><p key={name}>{count} × {min}–{max} · {name}</p>)}</section>)}</>}
createRoot(document.getElementById('root')).render(<App/>);
